name: tfsec-checkgen-validate
description: Run tfsec-checkgen validate.

inputs:
  tfsec_version:
    description: The tfsec version to download.
    required: false
    default: 1.28.0

outputs:
  custom_checks_valid:
    description: States if the custom checks are valid.

runs:
  using: docker
  image: dockerfile
  args:
    - ${{ inputs.tfsec_version }}
