name: tfsec-checkgen-validate
description: Run tfsec-checkgen validate.

inputs:
  custom_checks_directory:
    description: The directory containing your custom checks.
    required: false
    default: ./

  tfsec_version:
    description: The tfsec version to download.
    required: false
    default: 1.28.0

outputs:
  custom_checks_valid:
    description: Are the custom checks are valid.

runs:
  using: docker
  image: dockerfile
  args:
    - ${{ inputs.custom_checks_directory }}
